# Generated by Django 3.2 on 2021-04-18 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(choices=[(0, '未删除'), (1, '删除')], default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.IntegerField(choices=[(1, '风险题'), (2, '必答题'), (3, '抢答题'), (4, '双人对战')], default=1)),
                ('password', models.CharField(default='123456', max_length=6)),
                ('score', models.IntegerField(default=0)),
                ('question_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.questionlist')),
                ('test_record', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.testrecord')),
                ('user', models.ManyToManyField(to='api.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
