# Generated by Django 3.2 on 2021-04-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
    ]
