# Generated by Django 3.2 on 2021-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210418_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(default='123456', max_length=6, null=True),
        ),
    ]
