# Generated by Django 3.2 on 2021-04-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_room_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
