# Generated by Django 3.2 on 2021-04-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_room_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='password',
            field=models.CharField(default='123456', max_length=6),
        ),
    ]
