# Generated by Django 3.2 on 2021-05-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_wrong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wrong',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.question'),
        ),
    ]
