# Generated by Django 3.2 on 2021-05-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_wrong_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='questions',
            field=models.ManyToManyField(null=True, related_name='question_set', to='api.Question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='icon/default.JPG', upload_to='icon'),
        ),
    ]
