# Generated by Django 3.2 on 2021-05-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210507_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='questions',
            field=models.ManyToManyField(related_name='question_set', to='api.Question'),
        ),
    ]
