# Generated by Django 3.2 on 2021-05-08 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_questionlist_questions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerrecord',
            options={'verbose_name': '题目作答记录'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': '选项'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '题目'},
        ),
        migrations.AlterModelOptions(
            name='questionlist',
            options={'verbose_name': '题目集'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': '房间'},
        ),
        migrations.AlterModelOptions(
            name='testrecord',
            options={'verbose_name': '测试记录'},
        ),
        migrations.AlterModelOptions(
            name='wrong',
            options={'verbose_name': '错题'},
        ),
        migrations.AlterModelTable(
            name='answerrecord',
            table=None,
        ),
    ]
