# Generated by Django 3.2 on 2021-05-08 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210508_0027'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answerrecord',
            table='answer_record',
        ),
    ]
