# Generated by Django 3.2 on 2021-05-08 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_answerrecord_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name_plural': '房间'},
        ),
    ]
