# Generated by Django 3.2 on 2021-05-08 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerrecord',
            options={'verbose_name_plural': '题目作答记录'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name_plural': '选项'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '题目'},
        ),
        migrations.AlterModelOptions(
            name='questionlist',
            options={'verbose_name_plural': '题目集'},
        ),
        migrations.AlterModelOptions(
            name='testrecord',
            options={'verbose_name_plural': '测试记录'},
        ),
        migrations.AlterModelOptions(
            name='wrong',
            options={'verbose_name_plural': '错题'},
        ),
    ]
