# Generated by Django 3.2 on 2021-05-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210508_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '单选'), (2, '判断'), (3, '其他')], default=1),
        ),
    ]
