# Generated by Django 3.1.7 on 2021-03-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionlist',
            old_name='question',
            new_name='questions',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(1, '单选'), (2, '多选'), (3, '其他')], default=1),
        ),
    ]
