# Generated by Django 3.1.7 on 2021-03-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20210307_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerrecord',
            old_name='questio',
            new_name='question',
        ),
    ]
