# Generated by Django 3.1.7 on 2021-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20210307_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerrecord',
            name='question',
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='question',
            field=models.ManyToManyField(to='app01.Question'),
        ),
        migrations.DeleteModel(
            name='ChoseOptions',
        ),
    ]
