# Generated by Django 3.1.7 on 2021-03-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20210310_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerrecord',
            name='question',
        ),
        migrations.AddField(
            model_name='answerrecord',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app01.question'),
            preserve_default=False,
        ),
    ]
