# Generated by Django 3.1.7 on 2021-03-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_auto_20210310_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerrecord',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.question'),
        ),
    ]
